repo: "pyramidanalytics"
imagePullPolicy: "IfNotPresent"
unattended:
  enabled: false
  # Storage
storage:
  type: other
    # size: "10Gi"
    # nfs:
    #	path: "/"
    #	ip: "0.0.0.0"

# Web server
ws:
  port: 8282
  replicas: 1
  requests:
    memory: "2000Mi"
    cpu: "2000m"
    ephemeral_storage: "2Gi"
  limits:
    memory: "2000Mi"
    cpu: "2000m"
    ephemeral_storage: "4Gi"
  kedaAutoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    threshold: 180

# Request routing
rtr:
  replicas: 1
  requests:
    memory: "1000Mi"
    cpu: "2000m"
  limits:
    memory: "1000Mi"
    cpu: "3000m"

# Runtime engine
rte:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "8000Mi"
    cpu: "4000m"
  replicas: 1
  satellites: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilization: 70

# Natural language processing engine
nlp:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "8000Mi"
    cpu: "4000m"
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilization: 70

# Task engine
te:
  requests:
    memory: "4000Mi"
    cpu: "4000m"
    ephemeral_storage: "3Gi"
  limits:
    memory: "8000Mi"
    cpu: "8000m"
    ephemeral_storage: "10Gi"
  terminationGracePeriodSeconds: 300
  replicas: 1
  satellites: 2
  printers: 2
  kedaAutoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5

# Artificial intelligence server
ai:
  requests:
    memory: "4000Mi"
    cpu: "4000m"
    ephemeral_storage: "3Gi"
  limits:
    memory: "8000Mi"
    cpu: "8000m"
    ephemeral_storage: "5Gi"
  replicas: 1
  satellites: 2
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCpuUtilization: 70

# GeoSpatial server
gis:
  enabled: true
  requests:
    memory: "2000Mi"
    cpu: "1000m"
  limits:
    memory: "2000Mi"
    cpu: "2000m"