apiVersion: apps/v1
kind: Deployment
metadata:
  name: gis-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: pagis
  replicas: {{ if .Values.gis.enabled }}1{{ else }}0{{ end }}
  template:
    metadata:
      labels:
        app: pagis
        {{- include "pyramidAnalytics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: pa-service
      containers:
        - name: pagis
          image: "{{ .Values.repo }}/gis:{{ .Chart.AppVersion }}"
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            exec:
              command:
                - ./readiness.sh
          resources:
            limits:
              cpu: "{{ .Values.gis.limits.cpu }}"
              memory: "{{ .Values.gis.limits.memory }}"
            requests:
              cpu: "{{ .Values.gis.requests.cpu }}"
              memory: "{{ .Values.gis.requests.memory }}"
          env:
{{- include "pyramidAnalytics.baseEnv" . | nindent 12 }}
{{- include "pyramidAnalytics.containerSecurityContext" . | nindent 10 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
