apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: panlp
  replicas: {{.Values.nlp.replicas}}
  template:
    metadata:
      labels:
        app: panlp
        {{- include "pyramidAnalytics.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: panlp
          image: "{{ .Values.repo }}/nlp:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          readinessProbe:
            exec:
              command:
                - ./readiness.sh
          resources:
            limits:
              cpu: "{{ .Values.nlp.limits.cpu }}"
              memory: "{{ .Values.nlp.limits.memory }}"
            requests:
              cpu: "{{ .Values.nlp.requests.cpu }}"
              memory: "{{ .Values.nlp.requests.memory }}"
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "./stop_main_processes.sh"
                  ]
          env:
{{- include "pyramidAnalytics.baseEnv" . | nindent 12 }}
{{- include "pyramidAnalytics.containerSecurityContext" . | nindent 10 }}
{{- include "pyramidAnalytics.mount" . | nindent 6 }}
{{- include "pyramidAnalytics.volume" . | nindent 6 }}
{{- include "pyramidAnalytics.podSecurityContext" . | nindent 6 }}
