{{- if eq "NFS" $.Values.storage.type }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pyramid-storage-pv
  labels:
    name: pyramid-storage
spec:
  capacity:
    storage: {{$.Values.storage.size}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  mountOptions:
    - nfsvers=4
  nfs:
    path: {{$.Values.storage.nfs.path}}
    server: {{$.Values.storage.nfs.ip}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyramid-storage-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pyramid-storage-pv
  resources:
    requests:
      storage: {{$.Values.storage.size}}
---
{{- end }}