{{- if eq "GoogleStore" $.Values.storage.type }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pyramid-storage-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: google-filestore-storage-class
  resources:
    requests:
      storage: {{$.Values.storage.size}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-filestore-storage-class
  namespace: {{ .Release.Namespace }}
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default
{{- end }}