apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: base-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: [ "pods","persistentvolumeclaims" ]
    verbs: [ "get","list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: installer-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: pa-service
---
