apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: base-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get","list","create","delete","deletecollection" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "create", "delete", "list","deletecollection" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: installer-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: pa-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: installer-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: base-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: pa-service
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: installer-service
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: base-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: installer-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: installer-service
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: installer-role
  apiGroup: rbac.authorization.k8s.io
