apiVersion: v1
kind: Service
metadata:
  name: pyramid
  namespace: {{ .Release.Namespace }}
  labels:
    app: pyramid
    {{- include "pyramidAnalytics.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"  
    prometheus.io/path: "/metricsfull"
spec:
  selector:
    app: paws
  type: LoadBalancer
  ports:
    - name: "http"
      port: {{.Values.ws.port}}
      targetPort: 8181
    - name: "metrics"
      port: 9090
      targetPort: 9090
