{{- if .Values.te.kedaAutoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: te-scaled
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: task-service
  pollingInterval: 15
  cooldownPeriod: 10
  maxReplicaCount: {{.Values.te.kedaAutoscaling.maxReplicas}}
  minReplicaCount: {{.Values.te.kedaAutoscaling.minReplicas}}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-service.{{ .Release.Namespace }}.svc.cluster.local:9090"
        metricName: pyramid_te_scale
        threshold: {{.Values.te.kedaAutoscaling.threshold | quote }}
        query: max(pyramid_te_scale)
{{- end }}
