{{- if .Values.unattended.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: unattended-installation
  namespace: {{ .Release.Namespace }}
stringData:
{{- include "pyramidAnalytics.unattended.json" . | nindent 2 }}
{{- end }}
